### ISSUE TITLE
Images going out of bound

### ISSUE THREAD

**Issue by vishal-biyani** [themefisher/northendlab-hugo#6]
Images even after resizing go out of the main area of blog text. Is there a way to fix this automatically across the blog site?

![image](https://user-images.githubusercontent.com/1167948/78878012-56890400-7a6f-11ea-8b57-fbb62baffb85.png)

**Comment by Somrat37** [comment]
Hey there, thanks for your concern, i fixed this issue. please take a pull

**Comment by vishal-biyani** [comment]
Wow, thank you so much @Somrat37 for the quick fix, really appreciate it.

**Comment by sreeharshrajan** [comment]
Hi, I find the issue still prevails please help me! 
![image](https://user-images.githubusercontent.com/8036665/80419242-64a3a500-88f6-11ea-8059-91da4601dea9.png)
PS: I have tried with stock image in the screenshot.

**Comment by Somrat37** [comment]
@sreeharshrajan, please create a new issue.
